### ISSUE TITLE
Plugins fail to apply with jruby 1.7

### ISSUE THREAD

**Issue by CTrox** [elastic/puppet-elasticsearch#922] opened 2018-03-06 08:43 UTC
* Module version: 6.2.1
* Puppet version: 5.4
* OS and version: Ubuntu 16.04

## Bug description
Since version 6.2.1 it looks like the elastic_plugin provider is using `%i[]` which is not supported on jruby 1.7.x according to [this](https://github.com/jruby/jruby/issues/2771).

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/elasticsearch_plugin: Could not autoload puppet/provider/elasticsearch_plugin/plugin: /home/puppetcode/environments/production/upstream/elasticsearch/lib/puppet/provider/elastic_plugin.rb:110: unknown type of %string
      %i[host port user password].map do |param|
        ^ (file: /home/puppetcode/environments/production/upstream/elasticsearch/manifests/plugin.pp, line: 134, column: 3) (file: /home/puppetcode/environments/production/services/s_elasticsearch/manifests/plugins/migration.pp, line: 13) on node certname.nine.ch
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by fschaer** [comment] 2018-03-07 14:40
Same issue for me, puppet5 opensource

Workaround for this lies here : 
https://github.com/elastic/puppet-elasticsearch/blob/30763415b13b12061eb03570a7748464c1ebeb11/lib/puppet/provider/elastic_plugin.rb#L110

replace with :

`      [:host , :port , :user , :password].map do |param|`

**Comment by tylerjl** [comment] 2018-03-08 18:42
This was definitely a surprise, I was under the assumption that deprecating Puppet 3.x implied moving to Ruby 2.x wholesale but it does indeed seem that [Puppet Server leverages JRuby 1.7](https://github.com/puppetlabs/puppetserver#ruby-and-puppet-server), so we *will* need to continue to support Ruby 1.9.x across the board.

Thank you very much for the reports @CTrox and @fschaer, I'm going through the process of setting up failing tests to ensure that I can catch every instance that may cause problems like this and verifiably ensure that the problem is solved and will continue to be caught with tests in the future.

**Comment by tylerjl** [comment] 2018-03-13 18:50
[This went out in the 6.2.2 release](https://forge.puppet.com/elastic/elasticsearch/changelog#622-march-13-2018).

**Closed** 2018-03-13 18:50 UTC
Labels: bug
