### ISSUE TITLE
es_facts fail when attempting to make REST calls to HTTPS API endpoint

### ISSUE THREAD

**Issue by hex2a** [elastic/puppet-elasticsearch#838] opened 2017-05-31 11:42 UTC
## Bug description
The URI for elasticsearch in es_facts.rb is hardcoded and uses only HTTP:

```ruby
uri = URI("http://localhost:#{port}")
http = Net::HTTP.new(uri.host, uri.port)
http.read_timeout = 10
http.open_timeout = 2
response = http.get('/')
```

This causes errors when the elasticsearch API is listening for HTTPS traffic.

**Comment by tylerjl** [comment] 2017-05-31 16:39
Hey @hex2a,

I poked around this for a bit but don't know of a good way to solve this one. Although the custom fact _does_ parse the `elasticsearch.yml` configuration files it finds in order to determine how to connect to Elasticsearch, if a node is listening on HTTPS, that means that Elasticsearch must be using X-Pack to support TLS connectivity, which also means that the fact must provide some sort of authentication to talk to X-Pack secured API endpoints. Since there's no way (that I'm aware of) to pass parameters to custom facts, I'm not sure how we'd go about implementing this, unless you have some idea for a solution.

**Comment by hex2a** [comment] 2017-05-31 16:44
there are also elasticsearch plugin which provide TLS for the transport/HTTP API.

maybe, if the fact is defined instead of just added (for example as in https://github.com/Jimdo/facter/blob/master/lib/facter/ec2.rb ), it would be possible to block them using `blocklist` in `facter.conf` ?

**Comment by tylerjl** [comment] 2017-05-31 16:57
True; I had forgotten about other plugins to support TLS.

Is there a difference between calling `Facter.add` versus `Facter.define`? In either case, the custom Elasticsearch facts will just silently skip themselves if the API returns anything other than 200, so blocking them shouldn't be necessary.

The other concern is that if Elasticsearch is exposed over HTTPS, is there a way to  tell that a third-party plugin has enabled it by parsing `elasticsearch.yml`? And if the facts instead just try to hit both `http` and `https`, there's no way to configure settings for TLS/SSL verification or, alternatively, skipping TLS/SSL validity checks.

**Comment by tylerjl** [comment] 2017-05-31 17:44
Sorry, I think I may have misunderstood the intent of the ticket here - are you asking that the custom fact just silently skip adding the custom fact if it gets TLS connection errors when attempting to communicate with `http://localhost:9200`? Making the facts work with HTTPS endpoints can end up being kind of tricky, but catching failed requests in the same way the fact skips over non-200 response codes is doable (you lose the facts over TLS-endpoint Elasticsearch instances, but there shouldn't be failures anymore).

**Comment by hex2a** [comment] 2017-05-31 17:59
> is there a way to tell that a third-party plugin has enabled it by parsing elasticsearch.yml
this would need to be implemented for every plugin/option.

the problem is, that the fact tries to connect using HTTPS, this will show up in the error log as invalid connect.

the best way to disable this, would be the `blocklist` option in `facter.conf` (similar to disabling the built-in EC2 facts)

**Comment by tylerjl** [comment] 2017-05-31 18:09
> the best way to disable this, would be the blocklist option in facter.conf (similar to disabling the built-in EC2 facts)

If that's the case, is there anything to change in this module, given that managing the `facter.conf` file is probably outside its scope?

**Comment by hex2a** [comment] 2017-05-31 18:10
it does not seem to work.
Maybe the fact is only added after evaluation?

**Comment by tylerjl** [comment] 2017-05-31 18:37
The custom facts follow the typical way of defining facts, so I'm not sure what could change in terms of how they're evaluated. If there's a better way of defining custom facts so they can be properly blacklisted I'd be happy to do so, I'm just not aware what the required change here would be.

**Comment by mzahorik** [comment] 2017-08-08 13:48
I opened 863 for this same issue, not realizing this was the same based on title.

In 863 I note that this module sets xpack.security.http.ssl.enabled to true in elasticsearch.yml when SSL is enabled.  So if NOT gathering the facts is a viable solution, which given the current state is where we are anyways, a simple if !http.ssl.enabled wrapped around the http calls will suffice to eliminate the ES error messages on every facter run.

**Comment by tylerjl** [comment] 2017-08-08 17:31
Agreed; I think just choosing not to hit the API when SSL is enabled is the best option.

Moving forward, I think parsing that setting in the yml and skipping the REST call is the right way to go about it, I can either implement this once I've got time, or I'm happy to accept PRs (with tests 😄 ).

@mzahorik, if you feel like #863 is a dupe of this ticket, please go ahead and close it in favor of this one.

**Closed** 2017-08-15 22:51 UTC
Labels: bug

**Comment by hex2a** [comment] 2017-08-16 13:08
@tylerjl I submitted PR #865 for another plugin that provides HTTPS
