### ISSUE TITLE
Multi instance broken?

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#659] opened 2016-07-14 17:01 UTC
@tylerjl Just curious, as I thought I had this working, but it seems that multiple instances isn't working on same server anymore.
When I start "service elasticsearch-master start" elasticsearch-data dies (and vice versa).
ES version is `2.3.3-1`
OS is `CentOS Linux release 7.2.1511 (Core)`
puppet module is `0.11.0`
puppet version is `4.3.2`

Here are my configs, it might be stupid mistake on my part but any red herrings?:

```yaml
### MANAGED BY PUPPET ###
---
bootstrap:
  mlockall: true
cluster:
  name: vagrant-logging
discovery:
  zen:
    ping:
      multicast:
        enabled: false
      unicast:
        hosts:
             - esmaster:9201
http:
  port: 9200
index:
  number_of_replicas: 1
  number_of_shards: 5
network:
  host: _enp0s8_
node:
  data: true
  master: false
  name: esmaster-data
path:
  data: /var/lib/elasticsearch/data
  logs: /var/log/elasticsearch/data
```
```yaml
### MANAGED BY PUPPET ###
---
bootstrap:
  mlockall: true
cluster:
  name: vagrant-logging
discovery:
  zen:
    ping:
      multicast:
        enabled: false
      unicast:
        hosts:
             - esmaster:9201
http:
  port: 9201
index:
  number_of_replicas: 1
  number_of_shards: 5
network:
  host: _enp0s8_
node:
  data: false
  master: true
  name: esmaster-master
path:
  data: /var/lib/elasticsearch/master
  logs: /var/log/elasticsearch/master
```

and the esmaster is in the local hosts file so it should route fine:

`127.0.1.1       esmaster.vm.local       esmaster`

Let me know if there is anything else I can provide.

**Comment by tylerjl** [comment] 2016-07-14 17:20
I'm somewhat out of office at the moment, but I can think of a few places to look. As far as I remember, I've done 2.3.3 on CentOS 7 successfully in the past. Puppet should be managing the service via systemd units, so what are you seeing under `systemctl status $service` or the instances' logs?

**Comment by cdenneen** [comment] 2016-07-14 17:54
Yeah it worked for me too at one point so that's why I'm not sure what happened recently.
Yeah the "service" just redirects to systemctl.
Logs don't show anything because when you start the "other" the current one just gets killed so nothing logs... which seems true with the systemctl status `failed (Result: signal)`. So I originally thought maybe they were sharing same pid file... but the init_defaults look correct for both in sysconfig.

```
[root@esmaster elasticsearch]# systemctl status elasticsearch-master
● elasticsearch-master.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-master.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2016-07-14 12:52:38 EDT; 54min ago
     Docs: http://www.elasticsearch.org
  Process: 18986 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-master.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.work=${WORK_DIR} -Des.default.path.conf=${CONF_DIR} (code=exited, status=0/SUCCESS)
 Main PID: 18997 (code=killed, signal=KILL)

Jul 14 12:50:30 esmaster.vm.local systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
Jul 14 12:50:30 esmaster.vm.local systemd[1]: PID file /var/run/elasticsearch/elasticsearch-master.pid not readable (yet?) after start.
Jul 14 12:50:31 esmaster.vm.local systemd[1]: Started Starts and stops a single elasticsearch instance on this system.
Jul 14 12:52:38 esmaster.vm.local systemd[1]: elasticsearch-master.service: main process exited, code=killed, status=9/KILL
Jul 14 12:52:38 esmaster.vm.local systemd[1]: Unit elasticsearch-master.service entered failed state.
Jul 14 12:52:38 esmaster.vm.local systemd[1]: elasticsearch-master.service failed.
[root@esmaster elasticsearch]# systemctl status elasticsearch-data
● elasticsearch-data.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-data.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-07-14 12:52:37 EDT; 54min ago
     Docs: http://www.elasticsearch.org
  Process: 19059 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-data.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.work=${WORK_DIR} -Des.default.path.conf=${CONF_DIR} (code=exited, status=0/SUCCESS)
 Main PID: 19070 (java)
   CGroup: /system.slice/elasticsearch-data.service
           └─19070 /bin/java -Xms128m -Xmx128m -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiati...

Jul 14 12:52:36 esmaster.vm.local systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
Jul 14 12:52:36 esmaster.vm.local systemd[1]: PID file /var/run/elasticsearch/elasticsearch-data.pid not readable (yet?) after start.
Jul 14 12:52:37 esmaster.vm.local systemd[1]: Started Starts and stops a single elasticsearch instance on this system.
```

So for example if I start master now it just kills data

```
[root@esmaster elasticsearch]# systemctl start elasticsearch-master
[root@esmaster elasticsearch]# systemctl status elasticsearch-master
● elasticsearch-master.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-master.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-07-14 13:51:54 EDT; 3s ago
     Docs: http://www.elasticsearch.org
  Process: 19235 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-master.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.work=${WORK_DIR} -Des.default.path.conf=${CONF_DIR} (code=exited, status=0/SUCCESS)
 Main PID: 19246 (java)
   CGroup: /system.slice/elasticsearch-master.service
           └─19246 /bin/java -Xms128m -Xmx128m -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiati...

Jul 14 13:51:52 esmaster.vm.local systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
Jul 14 13:51:52 esmaster.vm.local systemd[1]: PID file /var/run/elasticsearch/elasticsearch-master.pid not readable (yet?) after start.
Jul 14 13:51:54 esmaster.vm.local systemd[1]: Started Starts and stops a single elasticsearch instance on this system.
[root@esmaster elasticsearch]# systemctl status elasticsearch-data
● elasticsearch-data.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-data.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Thu 2016-07-14 13:51:54 EDT; 5s ago
     Docs: http://www.elasticsearch.org
  Process: 19059 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-data.pid -Des.default.path.home=${ES_HOME} -Des.default.path.logs=${LOG_DIR} -Des.default.path.data=${DATA_DIR} -Des.default.path.work=${WORK_DIR} -Des.default.path.conf=${CONF_DIR} (code=exited, status=0/SUCCESS)
 Main PID: 19070 (code=killed, signal=KILL)

Jul 14 12:52:36 esmaster.vm.local systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
Jul 14 12:52:36 esmaster.vm.local systemd[1]: PID file /var/run/elasticsearch/elasticsearch-data.pid not readable (yet?) after start.
Jul 14 12:52:37 esmaster.vm.local systemd[1]: Started Starts and stops a single elasticsearch instance on this system.
Jul 14 13:51:54 esmaster.vm.local systemd[1]: elasticsearch-data.service: main process exited, code=killed, status=9/KILL
Jul 14 13:51:54 esmaster.vm.local systemd[1]: Unit elasticsearch-data.service entered failed state.
Jul 14 13:51:54 esmaster.vm.local systemd[1]: elasticsearch-data.service failed.
```

Almost like something changed in the systemd script that's KILL -9 "all found ES instances" before starting one.

**Comment by tylerjl** [comment] 2016-07-14 21:25
Indeed; the `KILL` is weird there. Anything in the ES logs?

**Comment by cdenneen** [comment] 2016-07-15 01:09
No since it is a KILL 9 it doesn't log anything.

**Comment by tylerjl** [comment] 2016-07-18 19:30
I reproduced your environment in a VM and got things to work. The only things I had to tweak a little were the network settings: since you're binding to an ethernet interface (`_enp0_`), I had to add the IP that address was listening under to `/etc/hosts` (since the service won't respond over 127). Otherwise, I'm able to manage the services fine; start/stop them independently, etc.

The only other thing I could think of is possibly the OOM killer nuking services on an undersized VM since you're locking memory? There would be system logs with that activity if it was happening.

**Comment by cdenneen** [comment] 2016-07-19 00:31
Can you share your profile with this working. I'd like to compare because
as you said the OOM error wouldn't be showing as KILL -9.

**Comment by cdenneen** [comment] 2016-07-19 11:05
@tylerjl I switched out the _enp0s8_ with _local_,_site_ and same issue happened... I tried to swap out network.host with "10.0.2.15" (local IP of the vm) and same issue.
I'm not sure what the differences are between my and your setup are. Opposite service still dying with KILL -9 so don't think it's an OOM thing. It's almost like they are trying to lock on to same resource (port, pid, lock, etc) and in order to start one it has to kill the other.

**Comment by tylerjl** [comment] 2016-07-19 15:13
Sure, here's a quick setup I put together that works (the nodes don't cluster for some reason, but that's beside the point, they start up in parallel just fine. It's just a weird issue with listening addresses I didn't have the time to debug).

```
$ tree
.
├── Vagrantfile
└── environments
    └── vagrant
        └── manifests
            └── default.pp

3 directories, 2 files
```

`Vagrantfile`:

```ruby
Vagrant.configure 2 do |config|

  config.vm.box = 'boxcutter/centos72'

  config.vm.provision 'shell',
    inline: <<-SCRIPT
      yum install -y ruby ruby-devel augeas-devel
      yum groupinstall -y "Development tools"
      gem install --no-rdoc --no-ri puppet --version 4.3.2
      ln -s /usr/local/bin/puppet /usr/bin/puppet
      gem install --no-rdoc --no-ri ruby-augeas
      puppet module install elasticsearch-elasticsearch
      puppet module install puppetlabs-java
    SCRIPT

  config.vm.provision 'puppet' do |puppet|
    puppet.environment = 'vagrant'
    puppet.environment_path = 'environments'
  end
end
```

`default.pp`:

```puppet
class { 'elasticsearch':
  java_install => true,
  repo_version => '2.x',
  manage_repo => true,
  version => '2.3.3',
  config => {
    'bootstrap.mlockall' => true,
    'cluster.name' => 'vagrant-logging',
    'index.number_of_replicas' => 1,
    'index.number_of_shards' => 5,
    'network.host' => '127.0.0.1',
  },
}

elasticsearch::instance { 'esmaster-data':
  config => {
    'http.port' => 9200,
    'discovery.zen.ping.multicast.enabled' => false,
    'discovery.zen.ping.unicast.hosts' => ['127.0.0.1:9201'],
    'node.data' => true,
    'node.master' => false,
  },
  datadir => '/var/lib/elasticsearch/data',
  logdir => '/var/log/elasticsearch/data',
}

elasticsearch::instance { 'esmaster-master':
  config => {
    'http.port' => 9201,
    'discovery.zen.ping.multicast.enabled' => false,
    'discovery.zen.ping.unicast.hosts' => ['127.0.0.1:9201'],
    'node.data' => false,
    'node.master' => true,
  },
  datadir => '/var/lib/elasticsearch/master',
  logdir => '/var/log/elasticsearch/master',
}
```

**Comment by cdenneen** [comment] 2016-07-20 11:46
@tylerlj ok so it turns out to be a memory thing.
If I disabled MAX_LOCKED_MEMORY=unlimited from init_config both instances come up.
If I increase the vm memory to 1g both instances come up.
Only change I made here was adding transport.port to both instances otherwise it seemed to sometimes crisscross 9200 with 9301.

So for single instance on vm with `bootstrap.mlockall: true` and `MAX_LOCKED_MEMORY=unlimited` the vm requires 512mb

For dual instance on vm with `bootstrap.mlockall: true` and `MAX_LOCKED_MEMORY=unlimited` the vm requires 1g

I really wish the underlying logging actually showed something like this. 
The fact that it sends a `KILL -9` is a bit weird too since it is memory related.
There has to be something in the underlying ES code that's causing this behavior, just think the logging was working.

**Comment by tylerjl** [comment] 2016-07-20 13:38
Closing since this isn't an issue with the puppet module.

While I do agree that the logging isn't very intuitive, there's really not much that Elasticsearch can do to highlight the root cause of the problem (and the puppet module can't do anything). If one instance attempts to lock 512M of memory, and another instance starts up with a similar request to the OS to lock the remaining memory of the VM, the instances are unaware of what the kernel is up to, and the only thing the first instance sees is a `-9` signal from (what I assume is) the OOM killer in order to make that later request physically possible. At that point all the JVM can do is die, and there's nothing more than a signal telling Elasticsearch why it's happening at all.

It definitely feels like this is just a matter of numbers adding up in the VM - i.e., if you wanted 2 instances up in a small VM, the other option is to just set the heap to something smaller (128M or 256M) and fit them side by side that way.

**Closed by tylerjl** 2016-07-20 13:38 UTC
Labels: triage

**Comment by cdenneen** [comment] 2016-07-20 14:26
@tylerlj the heap was set to 128m for each on a 512 machine.
Setting to 256 each on a 1gb vm is fine but so should be the latter...
