### ISSUE TITLE
Service fails to start on Debian 8

### ISSUE THREAD

**Issue by packi** [elastic/puppet-elasticsearch#369] opened 2015-06-11 07:20 UTC
The reason is that systemd starts ES as the user `elasticsearch` doesn't have write permissions to `/var/run/` and thus can't create the PID-directory and aborts when it can't write its PID-file to the non-existing directory.

Usage in puppet manifest:
```
    elasticsearch::instance {
        'es-01':
        ;
    }
```

Status after boot:
```
vagrant@host-01:~$ sudo service elasticsearch-es-01 status
● elasticsearch-es-01.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/lib/systemd/system/elasticsearch-es-01.service; enabled)
   Active: failed (Result: resources) since Don 2015-06-11 05:58:08 UTC; 7min ago
     Docs: http://www.elasticsearch.org
  Process: 451 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-es-01.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=0/SUCCESS)

Jun 11 05:58:08 host-01 elasticsearch[451]: - FileNotFoundException[/var/run/elasticsearch/elasticsearch-es-01.pid (No such file or directory)]
Jun 11 05:58:08 host-01 elasticsearch[451]: java.io.FileNotFoundException: /var/run/elasticsearch/elasticsearch-es-01.pid (No such file or directory)
Jun 11 05:58:08 host-01 elasticsearch[451]: at java.io.FileOutputStream.open(Native Method)
Jun 11 05:58:08 host-01 elasticsearch[451]: at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
Jun 11 05:58:08 host-01 elasticsearch[451]: at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
Jun 11 05:58:08 host-01 elasticsearch[451]: at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:162)
Jun 11 05:58:08 host-01 elasticsearch[451]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
Jun 11 05:58:08 host-01 systemd[1]: elasticsearch-es-01.service never wrote its PID file. Failing.
Jun 11 05:58:08 host-01 systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
Jun 11 05:58:08 host-01 systemd[1]: Unit elasticsearch-es-01.service entered failed state.
vagrant@host-01:~$ 
```

Starting it after boot fails as well:
```
vagrant@host-01:~$ sudo service elasticsearch-es-01 start
Job for elasticsearch-es-01.service failed. See 'systemctl status elasticsearch-es-01.service' and 'journalctl -xn' for details.
```

Adding the following lines to `/lib/systemd/system/elasticsearch-es-01.service` (or `templates/etc/init.d/elasticsearch.systemd.erb`) makes the service start as expected:
```
ExecStartPre=-/bin/mkdir /var/run/elasticsearch
ExecStartPre=/bin/chown -R elasticsearch:elasticsearch /var/run/elasticsearch/
PermissionsStartOnly=true
```

**Comment by electrical** [comment] 2015-06-11 08:09
weird that none of my tests show this issue so far.
Which version of the module are you using?

**Comment by bastelfreak** [comment] 2015-06-11 08:17
@packi which Operating system do you use? it is working fine with systemd on centos7:
```
# systemctl status elasticsearch-es-01.service -l
elasticsearch-es-01.service - Starts and stops a single elasticsearch instance on this system
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch-es-01.service; enabled)
   Active: active (running) since Wed 2015-06-10 14:14:39 CEST; 19h ago
     Docs: http://www.elasticsearch.org
  Process: 19290 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-es-01.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=0/SUCCESS)
 Main PID: 19297 (java)
   CGroup: /system.slice/elasticsearch-es-01.service
           └─19297 java -Xms16g -Xmx16g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch/elasticsearch-es-01.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.6.0.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.config=/etc/elasticsearch/es-01/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch/es-01 -Des.default.path.data= -Des.default.path.work= -Des.default.path.conf=/etc/elasticsearch/es-01 org.elasticsearch.bootstrap.Elasticsearch
```

my unit file:
```
[Unit]
Description=Starts and stops a single elasticsearch instance on this system
Documentation=http://www.elasticsearch.org

[Service]
Type=forking
EnvironmentFile=/etc/sysconfig/elasticsearch-es-01
User=elasticsearch
Group=elasticsearch
PIDFile=/var/run/elasticsearch/elasticsearch-es-01.pid
ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch-es-01.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR
# See MAX_OPEN_FILES in sysconfig
LimitNOFILE=65535
# See MAX_LOCKED_MEMORY in sysconfig, use "infinity" when MAX_LOCKED_MEMORY=unlimited and using bootstrap.mlockall: true

# Shutdown delay in seconds, before process is tried to be killed with KILL (if configured)
TimeoutStopSec=20

[Install]
WantedBy=multi-user.target
```

which is generated by this puppet profile (probably it isn't necessary to set the user/group so often, this once was a bug):
```
class profiles::elasticsearch {
  class { '::elasticsearch':
    repo_version  => '1.6',
    java_install  => true,
    manage_repo   => true,
    config        => { 'cluster.name' => 'elasticsearch_cluster_1' },
    elasticsearch_user  => 'elasticsearch',
    elasticsearch_group => 'elasticsearch',
    autoupgrade        => true,
  } ~>
  elasticsearch::instance { 'es-01': 
    config  => { 'node.name' => $::hostname },
    init_defaults => {
                        'ES_USER'       => 'elasticsearch', 
                        'ES_GROUP'      => 'elasticsearch', 
                        'user'          => 'elasticsearch', 
                        'group'         => 'elasticsearch',
                        'ES_HEAP_SIZE'  => '16g'},
  }
```

module version is 0.9.6

**Comment by philipwigg** [comment] 2015-06-11 08:22
@packi Are you calling the main class too?

i.e. I would expect to see both:-

```
include elasticsearch

elasticsearch::instance { 'es-01': }
```
@electrical That's necessary still right?

**Comment by electrical** [comment] 2015-06-11 08:22
@philipwigg that's correct :-)

**Comment by electrical** [comment] 2015-06-11 10:30
it does feel like the main class is missing or something since the main class creates any directories for the systemd / init script to place the pid file.

**Comment by darrenhaken** [comment] 2015-06-11 16:11
I am also facing this problem, any ideas?

**Comment by mstock** [comment] 2015-06-12 09:38
When running Puppet, the directory for the pid file does get created, and Elasticsearch starts. The problem is that when rebooting, the directory gets removed by some init script/systemd service (for SysV init, this is triggered by `/etc/init.d/mountall-bootclean.sh` and done by code in `/lib/init/bootclean.sh`, for systemd, I think `systemd-tmpfiles` is responsible for this). The init script for Elasticsearch (`templates/etc/init.d/elasticsearch.Debian.erb`) puts the pid file in `/var/run/$NAME.pid`, with `$NAME` being `elasticsearch-<%= @name %>`, which was `touch`ed and `chown`ed correctly by the init script. So somebody has to create the directory for the pid file on boot, and I think that should not be Puppet, but the init system instead ;).

**Comment by electrical** [comment] 2015-06-12 09:44
Interesting.
What if we just change the location of the pid file to `/var/run/$name.pid` instead of `/var/run/elasticsearch/$name.pid` ?
Would that solve the issue?

**Comment by darrenhaken** [comment] 2015-06-12 09:56
Sorry I'm experiencing this issue on Ubuntu not Debian. Looking in /var/run I can see the pid file is in this directory and not in elasticsearch
i.e. /var/run/$name.pid.

I do still see issues with permissions though.

**Comment by electrical** [comment] 2015-06-12 09:57
Hmm, interesting.. @darrenhaken could you share your puppet configs for ES?
Thanks!

**Comment by packi** [comment] 2015-06-12 11:27
Doesn't work with `/var/run/$name.pid` either and that wouldn't be how all other services do it (since Debian 7). The problem is that `/var/run` links to `/run`. And `/run` has the following permissions:
```
vagrant@host-01:~$ ls -latr / | grep run
drwxr-xr-x  25 root    root      900 Jun 12 11:14 run
vagrant@host-01:~$
```
So the `elasticsearch` user has no chance of creating a PID file or directory there. I'm a coworker of @mstock btw. so everything he said applies as well.

One solution would be the one I've outlined above, another one would be to add an entry to `tmpfiles.d` (see http://man7.org/linux/man-pages/man5/tmpfiles.d.5.html) to create the directory on startup.

**Comment by GlenRSmith** [comment] 2015-06-12 11:44
Related: https://github.com/elastic/elasticsearch/issues/11594

**Comment by electrical** [comment] 2015-06-12 13:43
I'm still confused that this is causing issues.
From what i understand directories get removed in the /var/run dir correct?
Why would it cause files not being able to managed in the /var/run dir?

And why wouldn't it show up at startup at all?
All the tests i run with the init scripts and systemd on different systems.

**Comment by mstock** [comment] 2015-06-12 16:06
Maybe I should mention that we're still on Elasticsearch 1.5.2 - as I just noticed, 1.6.0 seems to ship a `/usr/lib/tmpfiles.d/elasticsearch.conf`, which should ensure that this directory gets created by `systemd-tmpfiles` (at least at boot time). So I guess that current(ish) upstream versions of the Puppet module (like c1e5f01531f6a73774ec7e2c4ad0729a262013a1 that we patched locally for now) don't fully work as expected on Debian Jessie/8.0 (and maybe others) if the official Elasticsearch package in version < 1.6.0 is in use. This might explain why it works for some, but not for us and some others.

**Comment by electrical** [comment] 2015-06-12 16:22
@mstock I do most of my testing with 1.3.x versions of ES i have to admit. I'm working on getting better integration testing with different versions of ES so i catch weird issues earlier.
Also the puppet module should be creating the pid dir btw, but its possible indeed that the system boots, tries to launch ES while the elasticsearch sub dir is gone and not re-created by the puppet module.

As a solution i possibly could create the `/usr/lib/tmpfiles.d/elasticsearch.conf` file via puppet so we always will have that in place?

**Comment by electrical** [comment] 2015-06-12 16:25
@mstock @packi if this is a viable solution i'll try to get it in before doing a new release next week.

**Comment by mstock** [comment] 2015-06-12 19:08
@electrical I think that would be great :). I quickly tried this solution using 10336981e8434cc5d181fa9a75dff74d3912c37f of the Puppet module and by manually putting the file in place, and as far as I tried, it worked reliably: When the file was there, Elasticsearch was started after a reboot, if not, startup failed with the error about the pid file.

**Comment by electrical** [comment] 2015-06-12 20:21
@mstock thanks for the quick feedback. I'll get a PR up with the fix, would be great if you could try it out then before merging it just so we can confirm the fix is valid.
Unfortunately its a very specific thing that doesn't show up in any of my acceptance tests.

**Comment by electrical** [comment] 2015-06-12 21:04
@mstock @packi Could you guys try out #378 ? thanks!

**Comment by mstock** [comment] 2015-06-13 12:03
@electrical I quickly tried it, but it did not work yet, although the config file got created. However, the owner of the created `/var/run/elasticsearch`-directory gets set to `root:root` during reboot, which makes some sense since the config only contains

    d    /var/run/elasticsearch   0755   - -

while the version that would be installed by the 1.6.0 package would contain

    d    /var/run/elasticsearch   0755 elasticsearch elasticsearch - -

So it seems that user/group is missing. The reason for this seems to be that `$user` and `$group` get defined like this:

    $user = $elasticsearch::user
    $group = $elasticsearch::group

However, these values don't seem to exist, I guess it should be `$elasticsearch::elasticsearch_user` and `$elasticsearch::elasticsearch_group`, respectively.
Another potential problem I see (but I might have missed something) is that the file resource `/usr/lib/tmpfiles.d/elasticsearch.conf` can only be created on systems that already have a `/usr/lib/tmpfiles.d` directory, which may not be the case on systems without `systemd`-support (I guess that would for example affect CentOS/RHEL 6 which also have a defined `$pid_dir`, but afaik no `systemd`).

**Comment by electrical** [comment] 2015-06-13 16:37
Thanks for testing. The user /  group thing is my fault indeed. Stupid mistake. Will fix that soon.

For the second issue perhaps I should create a systemd variable and set it to true if systemd is used there and then place that file ?

**Comment by mstock** [comment] 2015-06-15 09:46
@electrical I think that should work, and maybe you can use the `$service_providers` variable that already gets defined in `elasticsearch::params` for this.

**Comment by electrical** [comment] 2015-06-15 10:48
@mstock thanks for the tip. Good idea indeed.
I've updated the PR, could you try it again? User/group thing should be fixed as well.
Thanks!

**Comment by packi** [comment] 2015-06-15 13:47
@electrical your PR works here, thanks!

**Comment by mstock** [comment] 2015-06-15 13:48
@electrical thanks for the update! I quickly tried the latest version of your PR, and as far as I tested it, it looks good. Elasticsearch starts up after a reboot, and the config in `tmpfiles.d` gets created, too, with the expected content.

**Comment by electrical** [comment] 2015-06-15 13:49
@packi @mstock great to hear! thanks for the feedback.
Merging it in today and hopefully doing a release this week.

**Closed** 2015-06-15 14:02 UTC
Labels: bug, in progress
