### ISSUE TITLE
shield role producing invalid YAML

### ISSUE THREAD

**Issue by laf-rge** [elastic/puppet-elasticsearch#636] opened 2016-05-18 05:02 UTC
I could be doing something wrong but here is what I have:
puppet manifest:

```

  elasticsearch::shield::role { 'admin':
    mappings   => ['cn=kibana-acl,ou=Groups,ou=Users,dc=X,dc=corp',],
    privileges => {
      'cluster' => 'all',
      'indices' => {
        'names'      => '*',
        'privileges' => ['all'],
      },
    },
  }
```

This produces the following roles.yml:

```
admin:
  cluster: all
  indices:
    privileges:
      - all
    names: "*"
```

Which doesn't parse and causes the following log in my elasticsearch.log:

```
[2016-05-17 21:51:33,145][ERROR][shield.authz.store       ] [lg10-instance] invalid role definition [admin] in roles file [/etc/elasticsearch/instance/shield/roles.yml]. could not resolve indices privileges [*]. skipping role...
```

**Comment by laf-rge** [comment] 2016-05-18 05:10
If I manually change the roles.yml to:
```
admin:
  cluster: all
  indices:
    - names: "*"
      privileges:
        - all   
```

Things work as expected but of course my changes are overwritten at the next puppet run.

**Comment by tylerjl** [comment] 2016-05-18 13:29
Yeah, this is the unfortunate ambiguity of yaml. In your case you want an array of hashes for `indices`, so wrapping the value for `indices` in brackets forms the yaml you want:

```
  elasticsearch::shield::role { 'admin':
    mappings   => ['cn=kibana-acl,ou=Groups,ou=Users,dc=X,dc=corp',],
    privileges => {
      'cluster' => 'all',
      'indices' => [{
        'names'      => '*',
        'privileges' => ['all'],
      }],
    },
  }
```
Creates:
```
$ cat /usr/share/elasticsearch/shield/roles.yml
---
admin:
  cluster: all
  indices:
    - names: "*"
      privileges:
        - all
```
Let me know if this fixes it.

**Comment by laf-rge** [comment] 2016-05-18 20:23
Here is the result:

```
admin:
  cluster: all
  indices:
    - privileges:
        - all
      names: "*"
```

which does not work.

**Comment by tylerjl** [comment] 2016-05-18 20:32
Gotcha. Could you share what version of Puppet, Elasticsearch, and Shield you're working with?

**Comment by laf-rge** [comment] 2016-05-18 20:35
Elasticsearch 2.3.2
Shield 2.3.2
Puppet 3.7.2

**Comment by tylerjl** [comment] 2016-05-18 22:07
Just wanted to follow-up quickly that I did reproduce this, apparently Shield doesn't parse valid yaml and expects `name` to be the first key in the list of hashes in the roles yaml file. It's pretty annoying behavior, and because ZAML (yaml library in use in Puppet < 4) doesn't dump hashes in sorted form, the problem can be intermittent.

Given some of the other obnoxious behaviors of ZAML, I'll probably just have to write something that returns the yaml in the form Shield expects.

Thanks for tracking this one down, I'll update this once I've got something put together.

**Comment by tylerjl** [comment] 2016-05-19 22:01
@laf-rge alright, this was kind of a hairy problem but for your case it should be fixed in [my bugfix branch](https://github.com/elastic/puppet-elasticsearch/compare/master...tylerjl:bugfix/shield-roles-yaml-order), feel free to test it out if you want to try it. **tl;dr** yaml order matters for some shield `.yml` files, the patch monkey patches `each_pair` so ZAML gets key/value pairs returned in order (recursively.)

The problem will still exhibit in Puppet >= 4 though, where the native `to_yaml` is in use rather than ZAML. This is probably significantly easier to solve, but I wanted to ensure this solution works before extending it to Puppet 4.

Work left for this to be merged and fixed is probably either to 1) adjusted the `extended` method to insert keys in sorted order (which Ruby > 1.8 will preserve) or 2) override `each` with sorted return values (which native `to_yaml` uses instead of `each_pair` in ZAML).

**Comment by laf-rge** [comment] 2016-05-20 04:11
Great! Now:

```
 44  elasticsearch::shield::role { 'admin':
 45     mappings   => ['cn=kibana-acl,ou=Groups,ou=Users,dc=domain,dc=corp',],
 46     privileges => {
 47       'cluster' => 'all',
 48       'indices' => [{
 49           'names'      => '*',
 50           'privileges' => ['all'],
 51       }],
 52     },
 53   }
```
produces:
```
admin:
  cluster: all
  indices:
    - names: "*"
      privileges:
        - all
```

Also we should update the Readme to reflect the proper way to encode the role (is it [{}]?).

I notice it takes two puppet runs for a config change to actually cause the roles.yml to write out. That could be peculiar to my environment.

**Closed** 2016-05-21 21:42 UTC
Labels: bug, in progress
