### ISSUE TITLE
Unable to set shield options when using SSL

### ISSUE THREAD

**Issue by fgimian** [elastic/puppet-elasticsearch#632] opened 2016-05-14 13:08 UTC
Hey guys, hope everyone is well.

@tylerjl was kind enough to implement initial Shield support, but sadly I'm encountering one rather important problem.

In our setup, we use LDAP authentication, so I set the following config in my instance:

```puppet
elasticsearch::instance { 'client-node':
  config => {
      ...
    # Shield configuration
    'shield' => {
      'authc.realms' => {
        # File-based Realm
        'file1' => {
          'type'  => 'file',
          'order' => '0',
        },
        # LDAP Realm
        'ldap1' => {
          'type'         => 'ldap',
          'order'        => '1',
          'url'          => $ldap_uris,
          'user_search'  => {
            'base_dn'   => 'ou=foo,dc=bar,dc=example,dc=com',
            # Disable the LDAP health check (constantly communicates with LDAP
            # and requires a Bind DN which we don't have)
            'pool'      => {
              'health_check' => {
                'enabled' => false
              },
            },
          },
          'group_search' => {
            'base_dn' => 'ou=foo,dc=bar,dc=example,dc=com',
          },
          # There appears to be a bug in Shield whereby the default LDAP
          # search time of 5s is not correctly implemented and thus
          # even very short LDAP lookups timeout with the following error:
          # cause: com.unboundid.ldap.sdk.LDAPSearchException: time limit exceeded
          #
          # Setting this to 120s appears to be sufficient to workaround the
          # problem.
          'timeout'      => {
            'ldap_search' => '120s',
          },
        },
      },
    },
    ...
```

However, as soon as I enable SSL like this:

```puppet
elasticsearch::instance { 'client-node':
  # SSL and certificates for Shield
  ssl                  => true,
  ca_certificate       => '/etc/openldap/cacerts/myca.pem',
  certificate          => '/var/tmp/cert.pem',
  private_key          => '/var/tmp/key.pem',
  keystore_password    => 'keystorepassword123',
  ...
```

My Shield settings are overwritten and I no longer have the ability to setup my LDAP authentication.

Perhaps I've missed something obvious?  Otherwise, would you please perform a recursive merge of SSL settings for Shield with any settings we provide in the config parameter?

Thanks so much!
Fotis

**Comment by tylerjl** [comment] 2016-05-14 16:20
Ah yep, this is a problem I overlooked, thanks for finding it @fgimian . For reference, I define the SSL/TLS configuration hash [here](https://github.com/elastic/puppet-elasticsearch/blob/995c1a9e92ead8cb33e5031e0a67cde8a5c49eb1/manifests/instance.pp#L284), then include it in the instance's config [in a merge function](https://github.com/elastic/puppet-elasticsearch/blob/995c1a9e92ead8cb33e5031e0a67cde8a5c49eb1/manifests/instance.pp#L383). 

Solutions to try:
* Manually handle keys in the hash the same way its done in [other parts of the manifest](https://github.com/elastic/puppet-elasticsearch/blob/995c1a9e92ead8cb33e5031e0a67cde8a5c49eb1/manifests/instance.pp#L235), it's explicit but messy.
* Try to rely on the deep hash merging in [puppet-datacat](https://github.com/richardc/puppet-datacat), though it hasn't been tested in this module and there may be a reason we aren't using it here in favor of the manual approach in other places.

**Comment by fgimian** [comment] 2016-05-15 09:58
@tylerjl Thanks mate, you might also be able to use the [`deep_merge` function in puppetlabs-stdlib](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/puppet/parser/functions/deep_merge.rb).

I think the manual approach is good too, and perhaps you could throw a `fail` if these keys have already been set by the user, so it's clear that you only do one or the other 😄 

I'll be here to test whichever solution you decide to go with buddy, just let me know when ready.

**Comment by tylerjl** [comment] 2016-05-16 18:04
@fgimian I think I've worked around this temporarily in 8f425f9, which I've added to an existing PR (#630) since that fixes some other shield config problems as well.

Fully-qualifying the tls config in the manifest isn't perfect, but I'm hoping to get some time to fix the root cause of these types of problems by controlling the configuration hash much more carefully so the behavior isn't as ambiguous and the manifests don't have to have so much `has_key` sort of detection everywhere.

**Comment by fgimian** [comment] 2016-05-16 21:50
Great job @tylerjl, just checked out the PR and that should do the trick for now I think. I'm on leave this week so I won't get to really play with it until Monday mate, but feel free to merge if you're comfortable with it. 😄 

Thanks so much for your help and support
Fotis

**Comment by tylerjl** [comment] 2016-05-18 15:18
Closing with the merge of #630, the root cause of this (messy hash handling) will be tracked in #633

**Closed by tylerjl** 2016-05-18 15:18 UTC
Labels: bug
