### ISSUE TITLE
bug elasticsearch

### ISSUE THREAD

**Issue by waelc** [elastic/puppet-elasticsearch#937] opened 2018-05-14 05:39 UTC
Dears

I installed elasticsearch and put configuration in the end file vi /etc/elasticsearch/elasticsearch.yml

 script.disable_dynamic: true
network.host: localhost
discovery.zen.ping.multicast.enabled: false
after that , I try to start services but i get has error

systemctl start elasticsearch

Job for elasticsearch.service failed because a configured resource limit was exceeded. See "systemctl status elasticsearch.service" and "journalctl -xe" for details.

systemctl status elasticsearch.service journalctl -l

● elasticsearch.service - Starts and stops a single elasticsearch instance on this system
Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: disabled)
Active: failed (Result: resources) since Sun 2018-05-13 13:55:40 +03; 1min 50s ago
Docs: http://www.elasticsearch.org
Process: 17682 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -d -p /var/run/elasticsearch/elasticsearch.pid -Des.default.config=$CONF_FILE -Des.default.path.home=$ES_HOME -Des.default.path.logs=$LOG_DIR -Des.default.path.data=$DATA_DIR -Des.default.path.work=$WORK_DIR -Des.default.path.conf=$CONF_DIR (code=exited, status=0/SUCCESS)
Process: 17679 ExecStartPre=/bin/chown -R elasticsearch:elasticsearch /var/run/elasticsearch/ (code=exited, status=0/SUCCESS)
Process: 17677 ExecStartPre=/bin/mkdir /var/run/elasticsearch (code=exited, status=1/FAILURE)

May 13 13:55:40 TVTC-clm2 systemd[1]: Starting Starts and stops a single elasticsearch instance on this system...
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "x$1"== "xstart" -o "x$1" == "xrestart" -o "x$1" == "xreload" -o "x$1" == "xforce-reload" ];then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: Ignoring invalid environment assignment 'if [ "$GET_ES_CONFIG_RETURN" !=0]; then': /etc/sysconfig/elasticsearch
May 13 13:55:40 TVTC-clm2 systemd[1]: PID file /var/run/elasticsearch/elasticsearch.pid not readable (yet?) after start.
May 13 13:55:40 TVTC-clm2 systemd[1]: elasticsearch.service never wrote its PID file. Failing.
May 13 13:55:40 TVTC-clm2 systemd[1]: Failed to start Starts and stops a single elasticsearch instance on this system.
May 13 13:55:40 TVTC-clm2 systemd[1]: Unit elasticsearch.service entered failed state.
May 13 13:55:40 TVTC-clm2 systemd[1]: elasticsearch.service failed.
Unit journalctl.service could not be found.

how i can solve this problem

**Comment by jarpy** [comment] 2018-05-14 06:57
If you are manually editing `elasticsearch.yml`, then I'd say that the issue is, by definition, unrelated to the Puppet module.

When you use Puppet to install Elasticsearch, does it run correctly before you make this manual change?

**Comment by jarpy** [comment] 2018-05-14 07:02
Appears to be a duplicate of elastic/elasticsearch#30554 .

**Comment by tylerjl** [comment] 2018-05-14 17:30
@jarpy is right; even many of those error messages, such as various pieces of shell logic in `/etc/sysconfig/elasticsearch` aren't just unrelated to this Puppet module, but lines of code that I don't believe appear in the upstream Elasticsearch packages as well - are you running in a heavily customized environment?

This repository is for development and support of the Puppet module, but I don't see any indication that this problem you're reporting is related to the Puppet module. If you're encountering issues with the Puppet module, then please do provide the information that you initially deleted in the issue template (Puppet version, example manifest, etc.) otherwise please feel free to ask this on the [discussion forums](https://discuss.elastic.co/) and we can close this.

**Comment by tylerjl** [comment] 2018-06-18 19:41
Closing due to inactivity.

**Closed by tylerjl** 2018-06-18 19:41 UTC
Labels: triage
