### ISSUE TITLE
install repo on debian failed :

### ISSUE THREAD

**Issue by DocEmmetBrown** [elastic/puppet-elasticsearch#268] opened 2015-02-13 12:33 UTC
Hi,

I tried to setup a clean install on a debian wheezy, with the repos.

In the machine manifest I wrote : 

  ```ruby
class { 'elasticsearch':
    version => '1.4.2',
    config => { 'cluster.name' => "$::hostname" },
    manage_repo => true,
    repo_version => '1.4',
  }
```

but I get this weird error from my apt module : 

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: validate_re(): "" does not match ["always", "daily", "weekly", "reluctantly"] at /etc/puppet/modules/apt/manifests/init.pp:66 on node <mynode>`

installing the repo aside, directly with the apt module works perfectly : 

```ruby
  apt::source { 'elasticsearch_14':
    comment           => 'elasticsearch 1.4',
    location          => 'http://packages.elasticsearch.org/elasticsearch/1.4/debian',
    release           => 'stable',
    repos             => 'main',
    key               => 'D88E42B4',
    key_source        => 'http://packages.elasticsearch.org/GPG-KEY-elasticsearch',
    pin               => '100',
    include_src       => false,
    include_deb       => true,
  }
```

My puppet master & client are 3.7 installed from puppetlabs. 
The apt module is puppetlabs-apt (v1.7.0)

Anybody has the same issue ?

Tell me if you need more details, logs, or anything else to pinpoint this issue ;)

Thanx

**Comment by electrical** [comment] 2015-02-16 11:39
I'll do some local testing, perhaps i missed something along the way since i test against a bit older version.

**Comment by electrical** [comment] 2015-02-16 13:43
I've done a local test with the module and latest puppetlabs-apt module and didn't run into any issues so far.
Do you have any other calls to the apt module in your manifests?

**Comment by DocEmmetBrown** [comment] 2015-02-18 09:08
Hi, sorry for the delay, I had to double check my manifests ;)

I'm using 'wdijkerman-zabbix' module, which uses apt module, but that's all ;) and didn't have any issues using this module with others modules or manifests...

**Comment by electrical** [comment] 2015-02-18 16:04
No worries.
Its very weird its having these issues.
I've done some tests with different puppetlabs-apt versions and have  seen no issues like this.
The repo part of the module pretty much only calls the apt::source part anyway so its weird it would fail at all.

**Comment by electrical** [comment] 2015-03-05 14:43
Hi,

I haven't been able to reproduce this issue at all with different puppet versions / puppetlabs-apt versions.

**Comment by DocEmmetBrown** [comment] 2015-03-05 15:03
Hi, thanx for your time. 

I guess my puppet setup must have something weird somewhere preventing this call to apt module... 

I'll keep you posted if I find the source of the issue !

Thanx again !

**Comment by electrical** [comment] 2015-03-24 14:21
@DocEmmetBrown did you manage to find anything about it?

**Comment by DocEmmetBrown** [comment] 2015-03-25 09:12
Hi,
no, I couldn't find any explanation for this behaviour... :disappointed:

**Comment by philipwigg** [comment] 2015-03-25 09:42
Can you search all your manifests and see if somewhere you are setting the $apt_update_frequency parameter in the apt class, and possibly leaving it undefined?

Maybe in Hiera data even?

That is what the error is complaining about.

Strangely the 'Usage' section for the puppet-apt module at https://github.com/puppetlabs/puppetlabs-apt#usage has an example where $apt_update_frequency is set to be undefined, which as far as I can tell would fail compilation with the exact error you're now experiencing. Maybe you've copied that?

**Comment by DocEmmetBrown** [comment] 2015-03-25 14:15
Hi Philip,

I searched recursively for this parameter in all my /etc/puppet folder, and no luck : 
It's only defined at its default value in the module definition : 
  $apt_update_frequency = 'reluctantly',
and I never set its value in any of my manifests...

**Comment by electrical** [comment] 2015-04-07 14:21
@DocEmmetBrown have you been able to track this down further? 
I haven't been able to reproduce this at all with any of my local testing.

**Comment by electrical** [comment] 2015-05-05 13:50
Closing issue after 28 days without an update. If its still an issue please open a new one.

**Closed by electrical** 2015-05-05 13:50 UTC

**Comment by DocEmmetBrown** [comment] 2016-09-22 10:10
@electrical : For the records, I finally found the bug, and solved the issue....
A very old custom 'apt' class, coded years ago that I had forgotten hidden somewhere in the loading path, that was overriding the 'apt' module sometimes... :/ 
Sorry for bothering you with my own bugs ;)

Cheers, and thank you for your hard work on this module.

**Comment by electrical** [comment] 2016-09-26 07:31
@DocEmmetBrown Thanks for coming back about the issue and glad you found it! :-)
