### ISSUE TITLE
Upgrading from 1.7 to 2.1

### ISSUE THREAD

**Issue by BurningTheSky** [elastic/puppet-elasticsearch#546] opened 2016-01-08 12:11 UTC
Hey,

What's the cleanest way to upgrade from 1.7 to 2.1? When I tried using the absent method to uninstall it doesn't seem to work and the service breaks and won't start when I upgrade to 2.1?

Thanks

**Comment by electrical** [comment] 2016-01-08 20:41
Hi,

When you change the `repo_version` and the `version` variables it should upgrade nicely in place.

**Comment by BurningTheSky** [comment] 2016-01-15 11:53
Sorry for the delay in replying, what is the best process? Stop the service on the server, update the puppet config on the puppet master then run puppet agent to upgrade config on the server?

**Comment by electrical** [comment] 2016-01-15 12:09
Hi,

if you modify the puppet part you can run the agent indeed to upgrade it.

**Comment by BurningTheSky** [comment] 2016-01-15 12:56
I tried using the steps I wrote but the service seems to fail:

# service elasticsearch status
elasticsearch dead but subsys locked
# service elasticsearch restart
Stopping elasticsearch:                             [FAILED]
Starting elasticsearch:                             [  OK  ]
# Exception in thread "main" java.lang.IllegalStateException: unable to upgrade the mappings for the index [ds_doc_store_systestix], reason: [Mapper for [container_id] conflicts with existing mapping in other types:
[mapper [container_id] has different [analyzer], mapper [container_id] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [container_id] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]]
Likely root cause: java.lang.IllegalArgumentException: Mapper for [container_id] conflicts with existing mapping in other types:
[mapper [container_id] has different [analyzer], mapper [container_id] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [container_id] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]
        at org.elasticsearch.index.mapper.FieldTypeLookup.checkCompatibility(FieldTypeLookup.java:117)
        at org.elasticsearch.index.mapper.MapperService.checkNewMappersCompatibility(MapperService.java:364)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:315)
        at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:261)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.checkMappingsCompatibility(MetaDataIndexUpgradeService.java:329)
        at org.elasticsearch.cluster.metadata.MetaDataIndexUpgradeService.upgradeIndexMetaData(MetaDataIndexUpgradeService.java:112)
        at org.elasticsearch.gateway.GatewayMetaState.pre20Upgrade(GatewayMetaState.java:228)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:87)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at <<<guice>>>
        at org.elasticsearch.node.Node.<init>(Node.java:202)
        at org.elasticsearch.node.Node.<init>(Node.java:129)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

**Comment by electrical** [comment] 2016-01-15 13:09
Okay that is an actual error with your mapping. That's something I can't solve with the puppet module :)

**Comment by BurningTheSky** [comment] 2016-01-15 13:21
It is something that has been changed by puppet though as the service started before I tried to do the upgrade.

**Comment by electrical** [comment] 2016-01-15 13:30
If you upgraded to 2.x that could be the cause since there have been some large changes for the mappings.

**Comment by BurningTheSky** [comment] 2016-01-15 13:55
In that case, what is the cleanest way to uninstall ES? When I try the absent method and then put 2.1 on I get the same error as above, it feels like it isn't removing everything properly?

**Comment by electrical** [comment] 2016-01-15 13:58
It doesn't remove the data by default which contains the mappings etc. You'll need to set the module to absent and then remove the data directory manually.

**Comment by BurningTheSky** [comment] 2016-01-15 13:59
Ok, out of interest, what does setting to absent do?

**Comment by electrical** [comment] 2016-01-15 14:05
It should remove the package and service script. it leaves the rest in place.

**Comment by electrical** [comment] 2016-01-16 10:37
Closing as its an ES issue and not related to the puppet module.

**Closed by electrical** 2016-01-16 10:37 UTC
