### ISSUE TITLE
Unable to install a plugin with v0.9.6

### ISSUE THREAD

**Issue by bastelfreak** [elastic/puppet-elasticsearch#350] opened 2015-06-01 10:03 UTC
I've the following manifest:
```puppet
  elasticsearch::plugin { 'lmenezes/elasticsearch-kopf':
    module_dir  => 'kopf',
    instances   => 'es-01',
    proxy_host  => 'proxy..de',
    proxy_port  => 3128,
  }
```

Which results in this error message:
```
# puppet agent -t 
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Info: Caching catalog for clusternode1..de
Info: Applying configuration version '1433151472'
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns: Usage:
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -u, --url     [plugin location]   : Set exact URL to download the plugin from
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -i, --install [plugin name]       : Downloads and installs listed plugins [*]
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -t, --timeout [duration]          : Timeout setting: 30s, 1m, 1h... (infinite by default)
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -r, --remove  [plugin name]       : Removes listed plugins
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -l, --list                        : List installed plugins
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -v, --verbose                     : Prints verbose messages
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -s, --silent                      : Run in silent mode
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:     -h, --help                        : Prints this help message
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns: 
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:  [*] Plugin name could be:
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:      elasticsearch/plugin/version for official elasticsearch plugins (download from download.elasticsearch.org)
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:      groupId/artifactId/version   for community plugins (download from maven central or oss sonatype)
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:      username/repository          for site plugins (download from github master)
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns: 
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns: Message:
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns:    Error while parsing options: ElasticsearchIllegalStateException: missing value for --url. Usage: --url [value]
Error: /usr/share/elasticsearch/bin/plugin -DproxyPort=3128 -DproxyHost=proxy..de -install lmenezes/elasticsearch-kopf -url  returned 64 instead of one of [0,1]
Error: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/Exec[install_plugin_lmenezes/elasticsearch-kopf]/returns: change from notrun to 0 1 failed: /usr/share/elasticsearch/bin/plugin -DproxyPort=3128 -DproxyHost=proxy..de -install lmenezes/elasticsearch-kopf -url  returned 64 instead of one of [0,1]
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/File[/usr/share/elasticsearch/plugins/kopf/.name]: Dependency Exec[install_plugin_lmenezes/elasticsearch-kopf] has failures: true
Warning: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Plugin[lmenezes/elasticsearch-kopf]/File[/usr/share/elasticsearch/plugins/kopf/.name]: Skipping because of failed dependencies
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/File[/lib/systemd/system/elasticsearch-es-01.service]: Dependency Exec[install_plugin_lmenezes/elasticsearch-kopf] has failures: true
Warning: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/File[/lib/systemd/system/elasticsearch-es-01.service]: Skipping because of failed dependencies
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Augeas[defaults_es-01]: Dependency Exec[install_plugin_lmenezes/elasticsearch-kopf] has failures: true
Warning: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Augeas[defaults_es-01]: Skipping because of failed dependencies
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Exec[systemd_reload_es-01]: Dependency Exec[install_plugin_lmenezes/elasticsearch-kopf] has failures: true
Warning: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Exec[systemd_reload_es-01]: Skipping because of failed dependencies
Notice: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Service[elasticsearch-instance-es-01]: Dependency Exec[install_plugin_lmenezes/elasticsearch-kopf] has failures: true
Warning: /Stage[main]/Profiles::Elasticsearch/Elasticsearch::Instance[es-01]/Elasticsearch::Service[es-01]/Elasticsearch::Service::Systemd[es-01]/Service[elasticsearch-instance-es-01]: Skipping because of failed dependencies
Notice: Finished catalog run in 75.87 seconds
```

Puppet ads -url to the exec but without a string, this shouldnt happen (see plugins.pp line 100-105). I don't know how validate_string() works, it looks like a whitespace god inserted (two whitespaces between -url and returned)?

```
-url  returned
```

let me know if you need further information.

**Comment by electrical** [comment] 2015-06-01 12:15
Unable to reproduce so far but I will improve the validation part which is incorrect.

**Comment by electrical** [comment] 2015-06-01 16:07
Been able to reproduce this with 3.8.x and future parser enabled.
#353 should fix this.

**Comment by bastelfreak** [comment] 2015-06-02 07:20
Bugfix is working fine now. Tested on Puppet 3.8.1 with future parser.

**Comment by electrical** [comment] 2015-06-02 07:53
Closing issue. Will be included with next release ( hopefully next week )

**Closed by electrical** 2015-06-02 07:53 UTC
Labels: bug
