### ISSUE TITLE
Systemd complains that ES service file is world-inaccessible

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-elasticsearch#934] opened 2018-05-09 03:26 UTC
* Module version: 6.2.2
* Puppet version: 4.10.11
* OS and version: Red Hat Enterprise Linux Server release 7.5 (Maipo)

Hi there, 

On every puppet run, I get the following warnings in /var/log/messages. 

> May  9 03:19:54 diehard systemd: Configuration file /usr/lib/systemd/system/elasticsearch-es-01.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
> May  9 03:19:54 diehard systemd: Reloading.

Could this be fixed by simply changing the mode of the service file for each instance? 

Thanks!
Nick

**Comment by nick-george** [comment] 2018-05-13 08:14
Thanks Tyler, 

Would you like me to file a PR for this? I figure it's worth fixing in the module rather than working around it elsewhere. 

Cheers, 
Nick

**Comment by Fabian1976** [comment] 2019-04-29 12:22
What is the status of this bug? I still see this message in the logs. (version 6.3.1)

**Comment by tylerjl** [comment] 2019-04-30 18:49
@Fabian1976 if the issue is still open then I don't think there's been any fixes committed/pull requests merged. I don't have an ETA on a fix but I'd be happy to review any community PRs :eyes:

**Comment by clev2k** [comment] 2019-06-19 08:19
Anyone picked this up yet?

**Comment by Fabian1976** [comment] 2019-07-17 12:52
It seems to be allready fixed by this commit: [bdd6ca32e5f5704e12292957f00a0ec470010ea9](https://github.com/elastic/puppet-elasticsearch/commit/bdd6ca32e5f5704e12292957f00a0ec470010ea9#diff-0cb67edf88dd57cc41161ee357e79fff), but a new version of the module has not yet been published.

**Comment by tylerjl** [comment] 2019-08-15 17:35
Really sorry about my delinquency here - I released 6.3.4 last week, which should include the aforementioned commit. :+1:

**Closed by tylerjl** 2019-08-15 17:35 UTC
Labels: bug
