### ISSUE TITLE
elasticsearch::plugin proxy_host, and proxy_port have no effect

### ISSUE THREAD

**Issue by andresvia** [elastic/puppet-elasticsearch#720] opened 2016-10-10 14:11 UTC
* Module version: 0.13.2
* Puppet version: 4.6.2
* OS and version: CentOS 7

## Bug description

elasticsearch::plugin proxy_host, and proxy_port have no effect because the elasticsearch plugin wrapper (`/usr/share/elasticsearch/bin/plugin`) doesn't use the ES_JAVA_OPTS environment variable

**Comment by tylerjl** [comment] 2016-10-10 14:16
Duplicate of #695, fixed in #717, fix will go out in the next release.

**Closed by tylerjl** 2016-10-10 14:16 UTC
