### ISSUE TITLE
Elasticsearch custom facts take extremely long

### ISSUE THREAD

**Issue by mzhaase** [elastic/puppet-elasticsearch#596] opened 2016-03-10 18:57 UTC
```
time sudo /opt/puppetlabs/bin/facter -p elasticsearch_9200_cluster_name
es-01

real    12m47.547s
user    0m3.908s
sys     0m0.144s

This happens for every fact I try.
```
Here is the config:

```
  $elasticversion = '1.7.5'
  package { 'openjdk-7-jre': ensure => 'installed' } ->
  class { 'elasticsearch':
    ensure => 'present',
    config => { 'cluster.name' => 'es-01',
      'network.host'           => $::ipaddress,
      'http.cors.enabled'      => true,
      'http.cors.allow-origin' => "'/https?:\\/\\/(grafana|localhost)(:[0-9]+)?/'",
    },
    package_url => "https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-${elasticversion}.deb",
  }->
  elasticsearch::instance { 'grafana-dash':
    config => { 'node.name' => 'grafana-dash' }
  }
```

**Comment by tylerjl** [comment] 2016-03-10 19:29
The elasticsearch facts just talk to elasticsearch - the slowness may be coming from Elasticsearch itself.

On this same setup, what does the following look like?

    time curl localhost:9200{,/_nodes/es-01}

**Comment by mzhaase** [comment] 2016-03-11 09:45
That returns immediately:

```
time curl localhost:9200{,/_nodes/es-01}
{
  "status" : 200,
  "name" : "grafana",
  "cluster_name" : "es-01",
  "version" : {
    "number" : "1.7.5",
    "build_hash" : "00f95f4ffca6de89d68b7ccaf80d148f1f70e4d4",
    "build_timestamp" : "2016-02-02T09:55:30Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
{"cluster_name":"es-01","nodes":{}}
real    0m0.217s
user    0m0.008s
sys     0m0.000s
```

**Comment by tylerjl** [comment] 2016-03-11 21:20
Hmm, I'm kind of at a loss there, the elasticsearch facts are fairly straightforward and the only potentially long/IO dependent operations are just REST calls. I'd suggesting using `strace` to possibly track the execution of facter to find where it seems to be stalled on your system.

**Comment by jarpy** [comment] 2016-03-14 22:17
There's a nasty trick that might be happening here. Even if you only ask Facter for one fact, it still runs them all. Example:
```
$ cat /opt/puppetlabs/facter/facts.d/do_not_run
#!/bin/sh
echo I told you not to run me >&2
echo i_ran=true

$ facter --json hostname
I told you not to run me
{
  "hostname": "rastahr"
}
```

If you're running Facter 2, you could try `facter --timing` to see how long each fact takes.

Facter 3 doesn't have that option (curses!). If you're on version 3, it might be worth temporarily installing Facter 2 just to do the profiling, assuming that the problem is replicated under Facter 2.

**Comment by mzhaase** [comment] 2016-03-15 10:21
I think I found the issue:
  
sudo strace -o ./facter_strace /opt/puppetlabs/bin/facter -p elasticsearch_9200_cluster_name

[...]
socket(PF_INET6, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_TCP) = 8
fcntl(8, F_GETFD)                       = 0x1 (flags FD_CLOEXEC)
fstat(8, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fstat(8, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
connect(8, {sa_family=AF_INET6, sin6_port=htons(9200), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)

The problem is that the node waits for IPv6 timeout for a long time, then retries a couple times.
I disabled IPv6 on the node and now the facts return way quicker.

Moral of the story: don't enable IPv6 if its not properly configured in your network.

**Comment by tylerjl** [comment] 2016-03-15 13:18
Excellent debug work, @mzhaase. Thank you for reporting your findings - hopefully this issue can help someone down the road if they run into a similar problem. 

There's a question of whether to resolve this problem at the fact layer since we're making REST calls, possibly by fast-failing on unresolvable addresses, but I think that's best left at the OS level. Closing.

**Closed by tylerjl** 2016-03-15 13:18 UTC
