### ISSUE TITLE
Just started to get this error. no parameter named 'ensure'

### ISSUE THREAD

**Issue by chad-upton** [elastic/puppet-elasticsearch#572] opened 2016-02-02 02:45 UTC
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'ensure' at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/package.pp:48 on File[/opt/elasticsearch/swdl] at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/package.pp:48 on node webapp.local.dev
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

elasticsearch.pp file
```
class sc::logstash (
  $package_url   =  'https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/rpm/elasticsearch/2.1.1/elasticsearch-2.1.1.rpm',
  $instance_name =  'logstash'
) {

  class { '::elasticsearch':
    autoupgrade                       =>  true,
    manage_repo                       =>  true,
    repo_version                      =>  '2.x',
    java_install                      =>  true,
  }

  elasticsearch::instance { $instance_name: }
}
```

**Comment by electrical** [comment] 2016-02-02 09:04
Duplicate of https://github.com/elastic/puppet-elasticsearch/issues/573

**Closed by electrical** 2016-02-02 09:04 UTC
