### ISSUE TITLE
Could not autoload puppet/provider/elasticsearch_user_file/oss_xpack

### ISSUE THREAD

**Issue by Celedhrim** [elastic/puppet-elasticsearch#982] opened 2018-09-11 07:21 UTC
* Module version: 6.3.3
* Puppet version: 4.10.12
* OS and version:Debian GNU/Linux 9.5 (stretch)

## Bug description

Hello,

I have install elasticsearch 6.3.2 with puppet module version 6.2.2 but I have the scripts symlink bug.

So I have update elasticsearch module to 6.3.3.
I have made change on my manifest to take care of change ( oss + repository)

But now when I try to apply manifest : 
```
 ~# puppet agent -t
Info: Using configured environment 'my_build_branch'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/oss_xpack: undefined method `oss_xpack_config' for Puppet::Type::Elasticsearch_user_file::ProviderOss_xpack:Class at /etc/puppetlabs/code/environments/my_build_branch/modules/elasticsearch/manifests/init.pp:555:6 on node my.server
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Have you an idea ? this was introduce in 6.3.0.

**Comment by tylerjl** [comment] 2018-09-11 19:36
Hi @Celedhrim, there's a possibility that this came up when you updated the module on the puppetmaster and the native types and providers changed. Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

**Comment by aadiwarden** [comment] 2018-09-11 23:39
We are seeing similar issues or our side.

Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/oss_xpack: undefined method `oss_xpack_config' for Puppet::Type::Elasticsearch_user_file::ProviderOss_xpack:Class at /etc/puppetlabs/code/environments/elastic6x_cfg/modules/elasticsearch/manifests/init.pp:545:6

**Comment by Celedhrim** [comment] 2018-09-12 07:15
> Hi @Celedhrim, there's a possibility that this came up when you updated the module on the puppetmaster and the native types and providers changed. Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

I've tried it before opening the issue , both puppet server and puppet agent, but same error

**Comment by Noles** [comment] 2018-09-12 15:45
I can confirm this with module version 6.3.3 and 6.3.2. 
6.3.1 does not show this error.

**Comment by tylerjl** [comment] 2018-09-12 16:15
Thanks everyone, this is important to get feedback to help figure out whether this is a bad bug or not ✅ 

@Celedhrim you mention this behavior was introduced in 6.3.0, and you're correct that things changed with the 6.3.0 release: [this diff shows that the provider was introduced in 6.3.0](https://github.com/elastic/puppet-elasticsearch/compare/6.2.2...6.3.0#diff-82e275d0c7e337acd40de95a8f7de62c), but [it requires the library that brings in that method like all the others](https://github.com/elastic/puppet-elasticsearch/compare/6.2.2...6.3.0#diff-82e275d0c7e337acd40de95a8f7de62cR1). 

@Noles, your case is even more perplexing because [the diff between the 6.3.1 release and 6.3.2 doesn't even touch any of the affected files](https://github.com/elastic/puppet-elasticsearch/compare/6.3.1...6.3.2), so I don't know how moving from a version like 6.3.1 to 6.3.2 could have possibly changed anything 🤔 

One thing to keep in mind with regards to these custom types and providers is that when they're changed or updated, [pluginsync](https://puppet.com/docs/puppet/5.3/plugins_in_modules.html#technical-details-of-pluginsync) _needs_ to be working correctly so that those ruby files are updated. I'm still trying to think of whether something on the module side could have caused this, though my current best guess is that something on the Puppet server or agent may be caching something incorrectly.

**Comment by ynnt** [comment] 2018-09-14 18:15
Seems like it's related to SERVER-84 Puppet bug.


The issue has gone after I merge updated module to all environments I have.

**Comment by bionicspy** [comment] 2018-09-24 12:13
Had same issue:
Module Version: 6.3.3
ES Version: 6.4.0 with x-pack
OS: CentOS 7.4

puppet-agent[xxxxx]: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/oss_xpack: no such file to load -- puppet/provider/elastic_parsedfile at /etc/puppetlabs/code/environments/development/modules/elasticsearch/manifests/init.pp:555:6 on node xxxx

digging into debug logs notice error reference to undef elasticsearch::security_plugin

added to
    class { 'elasticsearch':
...
        security_plugin => 'x-pack',
    }
this many or many not be the appropriate fix, but appears to have resolved issue for me.

**Comment by scamfield** [comment] 2018-11-06 09:37
Puppet Agent version: 5.5.6
Puppet Server version: 5.3.5
Module version: 6.3.3
OS and version:Debian GNU/Linux 9.5 (stretch)

We are seeing similar issues but only when the puppet server is restarted. And starts working on the 3rd re-try (with no changes).

`Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/elasticsearch_user: Could not autoload puppet/provider/elasticsearch_user/esusers: no such file to load -- puppet/provider/elastic_user_command (file: /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/init.pp, line: 554, column: 3)`

**Comment by tylerjl** [comment] 2018-11-06 20:14
@scamfield thanks for the info. Is this behavior (succeeding after multiple puppet runs) similar for others? I'm wondering if this is emerging from the Puppet server's caching mechanisms.

**Comment by tommoyangn** [comment] 2018-11-07 02:20
I can +1 what @scamfield reports - Success after 3 failed puppet runs following a server restart

**Comment by scamfield** [comment] 2018-11-07 10:58
@tylerjl I can confirm that after the 3rd run it continues to work until the next puppetserver restart. I've also done some testing by downgrading the module to see if its 6.3.x related after the big changes :

6.1.0 - works no errors
6.2.2 - works no errors
6.3.0 - fails with 500 error but works on 3rd run
6.3.1 - fails with 500 error but works on 3rd run
6.3.2 - fails with 500 error but works on 3rd run
6.3.3 - fails with 500 error but works on 3rd run

Reviewing the bugs open for 6.3.x, I think issue #990 may be related to this one.

**Comment by bakaie** [comment] 2018-11-14 17:56
Same issue here.  I have not made a change/upgrades to puppet or the module in several months. 

module version: 6.3.1

This was working with no issues until today.  I had all of my config in the pp role file and decided to move everything into hiera.  I started to have this issue after moving all the config into the yaml file.  I get the same 3 failed runs then one success.  
I have restarted the clients but not the puppet master.  If i just run the agent on the client over and over i get the same pattern, 3 failed one success.

**Comment by joernott** [comment] 2018-11-27 17:04
Our puppet guru and I tried to track down that issue today. It looks like these issues are related to the way you use confines in your providers. The selection of the provider is tied to the presence of /etc/elasticsearch/x-pack/roles.yml for xpack, respective other files for x-pack-oss and shield. Sadly, the error happens when compiling the catalog. This is long before these files are created.

As a result, the puppet run fails once for the role provider, once for the user provider (due to lines 554 / 555 in init.pp), then runs, which actually installs the package (offering the chance to have that file created).

I guess, a way to select the provider via some parameter instead of existence of a file which should be created by the module could solve that problem.

**Comment by tylerjl** [comment] 2018-11-28 00:16
Thanks for digging into it @joernott. Given that the module already accepts a parameter for `security_plugin`, I suppose we could use that, although we would need to differentiate between the plugin version of x-pack (< 6.3) and bundled x-pack (>= 6.3) since the config file paths are different between the two.

**Comment by Infraded** [comment] 2019-02-05 19:31
Any update on this? We're still seeing failures on these providers in our logs after any puppetserver restart.

**Comment by tylerjl** [comment] 2019-02-06 20:05
Given the complexities of trying to support multiple instances of ES _and_ very old versions, I think the cleanest solution will likely be making some backwards-incompatible changes in a major version release alleviate the need for the module to auto-detect these file paths.

**Comment by tobias-urdin** [comment] 2019-02-07 08:45
@tylerjl I assume you mean changing the `require` statement in the `elasticsearch_user` provider [1] to something like:

```
require File.join(File.dirname(__FILE__), '..','..','..', 'puppet/provider/elastic_user_command')
```
(And in all other places where it's required)

Would that really be disruptive? We've been using this in other modules and I dont think this would cause any issues, maybe I'm missing something

Best regards

[1] https://github.com/elastic/puppet-elasticsearch/blob/master/lib/puppet/provider/elasticsearch_user/esusers.rb

**Comment by tylerjl** [comment] 2019-02-08 19:23
@tobias-urdin can you confirm whether using that version of `require` resolves your issue? I'm still not sure there's a definitive reason that we've tracked down in this issue, but ruby failing to find a changed path in the puppet master's autoloaded environment sounds like the most plausible explanation. (my previous comment wasn't related to `require` statements in provider code, but it's what seems to make the most sense to me currently)

**Comment by tobias-urdin** [comment] 2019-02-08 23:42
@tylerjl I have not tested this approach on the puppet-elasticsearch module, I can maybe test this in a while if I have some time over.

**Comment by h0tw1r3** [comment] 2019-02-28 03:15
Patched as suggested., running in production.
https://github.com/btolab/puppet-elasticsearch/tree/fix-autoload-provider

**Comment by zez3** [comment] 2019-05-14 23:42
I tested and it works
There are 3 files that need to be touched

#egrep -r "elastic_user_command" /etc/puppetlabs/code/environments/development/modules/elasticsearch/lib/puppet/provider/

/etc/puppetlabs/code/environments/development/modules/elasticsearch/lib/puppet/provider/elasticsearch_user/elasticsearch_users.rb:require 'puppet/provider/elastic_user_command'
/etc/puppetlabs/code/environments/development/modules/elasticsearch/lib/puppet/provider/elasticsearch_user/users.rb:require 'puppet/provider/elastic_user_command'
/etc/puppetlabs/code/environments/development/modules/elasticsearch/lib/puppet/provider/elasticsearch_user/esusers.rb:#require 'puppet/provider/elastic_user_command'

I ended up with some ugly sed 

sed -i 's/require '\''puppet\/provider\/elastic\_user\_command'\''/require File\.join\(File\.dirname\(\_\_FILE\_\_\)\, '\''\.\.'\''\,'\''\.\.'\''\,'\''\.\.'\''\, '\''puppet\/provider\/elastic\_user\_command'\''/' /etc/puppetlabs/code/environments/development/modules/elasticsearch/lib/puppet/provider/elasticsearch_user/*

Why is this fix not yet merged ?

**Comment by hboetes** [comment] 2019-05-16 10:37
@h0tw1r3 could you be so kind as to create a pull request?

**Comment by juliantaylor** [comment] 2019-05-28 21:21
I too can confirm that this fixes the failures and I have created a PR with the change.

**Comment by smasa90** [comment] 2019-06-20 00:11
After some research, I found a ticket which semms relating this issue. -> https://tickets.puppetlabs.com/browse/PUP-3513
It seems to be due that puppetserver doesn't generate types/provisers from freshly pulled modules for a specific environment.

**Closed** 2019-08-20 22:00 UTC
Labels: triage

**Comment by webzakimbo** [comment] 2019-08-21 10:32
> Issuing a `puppet generate types --environment {env}` directly after a `puppet-code deploy`

Double thumbs up on this!

**Comment by mvilain** [comment] 2020-01-24 22:30
6.4.0 still throws this error unless you do 

puppet generate types --environment {env}

after r10k deploy or a puppet-code deploy
