### ISSUE TITLE
Elasticsearch has changed the logging with version 5.1 and greater so that logging.yml is no longer used.

### ISSUE THREAD

**Issue by tarp2699** [elastic/puppet-elasticsearch#797] opened 2017-03-22 15:28 UTC
Elasticsearch has changed the logging with version 5.1 and greater so that logging.yml is no longer used.

Can you update the module to use log4j2.properties with newer versions of ES.

* Module version: 5.1.0
* Puppet version: pe 2016.5
* OS and version: RHEL 6 64bit

## Bug description
This warning is displayed when starting.
 [2017-03-22T10:25:12,988][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/etc/elasticsearch/isgeis/logging.yml], logging is configured via [/etc/elasticsearch/isgeis/log4j2.properties]

**Comment by tylerjl** [comment] 2017-03-22 15:29
Duplicate of #747.

**Closed by tylerjl** 2017-03-22 15:29 UTC
Labels: duplicate
