### ISSUE TITLE
installation fails when plugin already existing

### ISSUE THREAD

**Issue by tobiasschaber** [elastic/puppet-elasticsearch#734] opened 2016-11-18 10:50 UTC
Hi,

if I install elasticsearch via puppet and hiera, and add this to my hiera:

elasticsearch::plugins:
  x-pack:
    instances:
      - es-01

re-provisioning fails with the following result:

==> elkmaster1: ERROR: plugin directory /usr/share/elasticsearch/plugins/x-pack already exists. To update the plugin, uninstall it first using 'remove x-pack' command> at 168:/etc/puppet/modules/elasticsearch/manifests/plugin.pp

Maybe I'm doing something wrong but it looks like idempotence is not guaranteed here.

Kind regards,
Tobias

**Comment by tylerjl** [comment] 2016-11-18 15:50
I @tobiasschaber, can you report:

- The module version this occurs on
- The Linux distro and version
- What version of Elasticsearch (and/or the `class { 'elasticsearch' :` part)
- Puppet version

**Comment by MoisesRT** [comment] 2016-11-21 10:48
Hi @tylerjl, I am having the same issue.
here is my report:
The error I am receiving after first instalment is
> Invalid parameter proxy on Elasticsearch_plugin[discovery-ec2]
Module: discovery-ec2
Linux: Ubuntu 14.04.3 LTS
ES: 5.0.1
Puppet: 3.4.3 on the node and 3.8.4 on the master

**Comment by tobiasschaber** [comment] 2016-11-21 13:10
Hey @tylerjl,
I am using:
module version: 0.15.0
linux: centos-6.7
elasticsearch 5.0.1
puppet: 3.8.7-1

This is my class part:

    class { 'elasticsearch' :
        ensure => present,
        status => enabled,
    }

Kind regards,
Tobias

**Comment by tylerjl** [comment] 2016-11-21 16:00
Have you tried following the error message to remove the plugin before re-running puppet?

That error message appears because puppet drops additional metadata into the plugin directory when it manages plugins for you in order to better guess plugin versions, and those bits of metadata aren't present in plugins you installed by hand so puppet tries to install the plugin regardless. Removing all manually installed plugins and letting puppet handle them should create the metadata and make any future runs idempotent.

**Comment by MoisesRT** [comment] 2016-11-21 19:34
@tylerjl 
I didn't installed the plugin manually,
I get the following message at the second puppet run:

> Error: /Stage[main]/Logzio-elasticsearch/Elasticsearch::Plugin[discovery-ec2]/Elasticsearch_plugin[discovery-ec2]: Could not evaluate: undefined method `scan' for nil:NilClass

Thanks

**Comment by tylerjl** [comment] 2016-11-21 19:40
Interesting - what is the output of `/usr/share/elasticsearch/bin/elasticsearch -version` on the system?

**Comment by MoisesRT** [comment] 2016-11-21 19:41
Version: 5.0.1, Build: 080bb47/2016-11-11T22:08:49.812Z, JVM: 1.8.0_111

**Comment by tylerjl** [comment] 2016-11-21 20:06
@MoisesRT hmm, the only place that could happen in the code is [here](https://github.com/elastic/puppet-elasticsearch/blob/eb8f333e3b2208e6bbcecc590617ae827ca13138/lib/puppet/provider/elastic_plugin.rb#L172) after a call to get the Elasticsearch version [here](https://github.com/elastic/puppet-elasticsearch/blob/eb8f333e3b2208e6bbcecc590617ae827ca13138/lib/puppet/provider/elastic_plugin.rb#L164). However, since you were able to call it successfully from the command line I'm not really sure what may be going on in your environment. I'd suggest start at trying your puppet runs with the `--trace` flag on and see what you can find as there's not much more I can dig into from here.

**Comment by bluebenno** [comment] 2016-11-24 00:47
I got the same errors during some puppet runs - but never on initial puppet run -  "Error: /Stage[main]/Elasticsearch/Elasticsearch::Plugin[repository-s3]/Elasticsearch_plugin[repository-s3]: Could not evaluate: undefined method `scan' for nil:NilClass".  As it turns out the memory available on my smallish ec2 instance (with no swap) was marginal.

The command /usr/share/elasticsearch/bin/elasticsearch -version , could produce a 'Cannot allocate memory' error.

Hope this helps (I can see a post above where it did run)

**Comment by tylerjl** [comment] 2016-11-29 19:03
Ah, interesting @bluebenno! This makes sense given that ES may be allocating too much memory for the JVM (depending user settings) if ES has already locked some for a running instance. Good catch.

Whether that is the root cause or not (which I suspect it may be), [given some of the work I did for version detection of 5.x](https://github.com/elastic/puppet-elasticsearch/blob/903e8129b4c6207d23f53e451242b4ac8a3534eb/lib/puppet_x/elastic/es_versioning.rb), we may actually be able to use that (which relies on the puppet resource `package[elasticsearch]` to find the installed version) instead of explicitly invoking `elasticsearch -version` which has historically been a little problematic (due to things like version strings from stdout, java paths, etc).

Once some of the bugs have been shaken out from this approach (see #744 and #746 for some pending fixes), we can probably replace the call to `elasticsearch -version` with the other approach. Given the results of debugging the issue here, I think it's probably the best shot at solving the issue given nothing nothing else seems to stick out.

**Comment by danhooper** [comment] 2016-12-22 16:10
@tylerjl @bluebenno I too am seeing this error.  However I have plenty of free memory and can run the -version command manually.  

I am running:
module version: 0.14.0
linux: centos-6.8
elasticsearch 2.4.1
puppet: 4.8.1

Here is the trace I get when debug is enabled:

```
Debug: Executing: '/usr/share/elasticsearch/bin/elasticsearch -version'
Error: /Stage[main]/Gbsp::Resource::Elasticsearch/Elasticsearch::Plugin[delete-by-query]/Elasticsearch_plugin[delete-by-query]: Could not evaluate: undefined method `scan' for nil:NilClass
/etc/puppetlabs/code/environments/production/modules/elasticsearch/lib/puppet/provider/elastic_plugin.rb:172:in `ensure in es_version'
/etc/puppetlabs/code/environments/production/modules/elasticsearch/lib/puppet/provider/elastic_plugin.rb:173:in `es_version'
/etc/puppetlabs/code/environments/production/modules/elasticsearch/lib/puppet/provider/elastic_plugin.rb:16:in `exists?'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property/ensure.rb:81:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1070:in `retrieve'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1098:in `retrieve_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:300:in `from_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:20:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:230:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:246:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:386:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:385:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:154:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:222:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:142:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:221:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:222:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:170:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:343:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:221:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:241:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:195:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:350:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:274:in `block in main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:241:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:225:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:170:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:540:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```

**Comment by tylerjl** [comment] 2017-01-20 16:50
With #763 and #770, both X-Pack (mentioned in the original issue comment) and version discovery without invoking the `elasticsearch` executable are now merged, so do raise a flag if this behavior continues to occur.

**Closed by tylerjl** 2017-01-20 16:50 UTC
Labels: triage
